markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Cavan Klinsky
url: http://zachholman.com
description: I make stuff
twitter: klinskyc
github: klinskyc
gravatar_url: /images/cjk_twitter.png
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-26045128-7'